# Generated by Django 3.1.5 on 2021-01-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210120_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
