version: "3.9"

services: 
  db:
    image: postgres:11
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: gunicorn pennytrust_backend.wsgi -b 0.0.0.0:8000
    environment: 
      - ENVIRONMENT=production
      - DEBUG=False
      - SECRET_KEY=sodeiqdoh)erbz3k1-#ugli)!y_y7s82joj&)3*48kezsq+_gc
    ports: 
    - 8000:8000
    depends_on: 
    - db


   

